# -*- org -*-
# +TITLE: 技巧汇兑 
* Cpp
#+INCLUDE: "./cpp.org" 
* wireshark 过滤出有数据的记录
过滤出有数据的记录: tcp.len>0  
过滤出有什么数据的记录: tcp.len>0   && tcp contains  f0:22:00:00 
如:查找本机和 10.1.1.5 包含 FF:01:00 的报文
#+BEGIN_SRC   python 
 ip.addr== 10.1.1.5 and tcp.len>0 and tcp contains FF:01:00
#+END_SRC  

* cmake 
** 生成 compile_commands.json 
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1  ../

rc -J  #=> rdm

** 查看编译时  运行的完整命令
#+BEGIN_SRC   bash
cd build #makefile 所在位置
make VERBOSE=t
#+END_SRC  


** 编译某一个文件

#+BEGIN_SRC   bash
cd build
make xxxx.cpp.o 
#+END_SRC  


* TIME_WAIT
可以看到红线所划的22点附近，TIME_WAIT监控值骤然下降，速度飞快，效果十分明显！

 

http://blog.sina.com.cn/s/blog_4a8d06ce0100lkgg.html
具体操作：
vi /etc/sysctl.conf

编辑文件，加入以下内容：
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
net.ipv4.tcp_fin_timeout = 30
然后执行 /sbin/sysctl -p 让参数生效。

* 端口关闭&打开
二、关闭端口号:iptables -A INPUT -p tcp --drop 端口号-j DROP
　　iptables -A OUTPUT -p tcp --dport 端口号-j DROP
三、打开端口号：iptables -A INPUT -ptcp --dport  端口号-j ACCEPT

* 查看程序开启的时间
ps -eo pid,lstart,cmd

* core 文件 产生配置
　使用ulimit -a可以查看系统core文件的大小限制;使用ulimit -c [kbytes]可以设置系统允许生成的core文件大小，例如

　　ulimit -c 0 不产生core文件

　　ulimit -c 100 设置core文件最大为100k

　　ulimit -c unlimited 不限制core文件大小

　除此之外，还可以在/proc/sys/kernel/core_pattern里设置core文件的文件名模板，详情请看core的官方man手册
* core 文件调试
gdb 程序名 core文件
如 gdb mole_online core.2833
 
进入后

** 命令: bt
列出调用函数的堆栈
    
** 命令: fr  [n]
进入 那个函数 n为调用函数在堆栈中的位置

** 命令: p 
打印变量
* mysql 语句
** kaoqin
 insert ignore into  t_kaoqin_machine_adminid select 14, adminid,auth_flag from t_kaoqin_machine_adminid where machine_id =2;
** insert  ignore 
#+BEGIN_SRC   sql
insert ignore into db_ejabberd.users  select userid,passwd,0 from db_account.t_user_info  ;
#+END_SRC  



** ALTER TABLE t1 CHANGE id id BIGINT NOT NULL

** 授权

#+BEGIN_SRC  sql 
GRANT select ON UMAN.* TO dbser@localhost 
      IDENTIFIED BY 'something';

GRANT all ON *.* TO   vuser@10.1.1.88 IDENTIFIED BY 'vuser';
GRANT all ON *.* TO   root@192.168.0.5 IDENTIFIED BY 'ta0mee';
GRANT all ON *.* TO   root@localhost IDENTIFIED BY 'ta0mee';
GRANT all ON *.* TO   root@'%' IDENTIFIED BY '123456';
GRANT all ON db_weiyi.* TO   root@"%" IDENTIFIED BY 'ta0mee';
GRANT all ON db_question_bank.* TO   question_user@"%" IDENTIFIED BY 'ta0mee';
GRANT all ON db_message.* TO   message_user@"%" IDENTIFIED BY 'ta0mee';
GRANT all ON *.* TO   root@"%" IDENTIFIED BY 'ta0mee';
GRANT all ON db_question.* TO   root@192.168.1.3 IDENTIFIED BY 'ta0mee';
GRANT all ON db_question.* TO   root@192.168.1.6 IDENTIFIED BY 'ta0mee';
GRANT all ON db_question.* TO   root@monitor.weiyi.com IDENTIFIED BY 'ta0mee';
GRANT all ON db_question.* TO   root@10.163.172.147 IDENTIFIED BY 'ta0mee';
GRANT all ON information_schema.* TO   root@localhost IDENTIFIED BY 'ta0mee';
 GRANT all ON information_schema.* TO   root@localhost IDENTIFIED BY 'ta0mee';


GRANT all ON db_question.* TO   root@MiWiFi-R1CM IDENTIFIED BY 'ta0mee';
GRANT all ON db_class.* TO   user_class@'%'  IDENTIFIED BY '14285714';


GRANT ALL PRIVILEGES ON *.* TO root@192.168.1.3 IDENTIFIED BY 'ta0mee' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO root@dev.www.yb1v1.com IDENTIFIED BY 'ta0mee' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO root@192.168.0.128 IDENTIFIED BY 'ta0mee' ; 
FLUSH PRIVILEGES;

GRANT  FLUSH;

192.168.0.128
GRANT all ON *.* TO   yb_user@localhost IDENTIFIED BY 'yb142857';
    
grant all privileges on ejabberd.* to ejabberd@10.1.14.57 IDENTIFIED BY "ejabberd";

	GRANT select ,delete,update,insert  ON db_tls_admin.* TO    tls_admin@localhost
      IDENTIFIED BY 'ta0mee';

GRANT select ,delete,update,insert  ON db_tls.* TO    tls_admin@localhost
      IDENTIFIED BY 'ta0mee';
#+END_SRC  



** create table
#+BEGIN_SRC  sql 

CREATE TABLE t_20140523_zongzi (
  userid  int(10)  unsigned NOT NULL default '0',
  zongzi_1_count int(10) unsigned NOT NULL default '0' COMMENT '每种粽子的个数', 
  zongzi_2_count int(10) unsigned NOT NULL default '0',
  zongzi_3_count int(10) unsigned NOT NULL default '0',
  zongzi_4_count int(10) unsigned NOT NULL default '0',
  zongzi_5_count int(10) unsigned NOT NULL default '0',
  opt_date    int(10) unsigned NOT NULL default '0' COMMENT '最后操作日期',  
  opt_date_count    int(10) unsigned NOT NULL default '0' COMMENT '当天抽了几次',  
  opt_itemid  int(10) unsigned NOT NULL default '0' COMMENT '这次应该得到的物品',   
  opt_state   int(10) unsigned NOT NULL default '0'   COMMENT '这次状态:0 未领取,1:已领取',   
  PRIMARY KEY  (userid )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE t_sysargs (
  arg_key int(10) unsigned NOT NULL default '0',
  arg_value int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (arg_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE t_opt_log (
  logtime int(10) unsigned NOT NULL default '0',
  userid int(10) unsigned NOT NULL default '0',
  logtype int(10) unsigned NOT NULL default '0',
  opttype int(10) unsigned NOT NULL default '0',
  itemid int(10) unsigned NOT NULL default '0',
  itemcount int(10) unsigned NOT NULL default '0',
  data_ex  int(10) unsigned NOT NULL default '0',
  KEY  (userid,logtime)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;





CREATE TABLE `t_union` (
  `area_id` smallint(5) unsigned NOT NULL default '0',
  `union_id` int(10) unsigned NOT NULL default '0',
  `create_time` int(10) unsigned NOT NULL default '0',
  `name` char(32) NOT NULL default '0',
  `declaration` varchar(256),
  `level` smallint(5) unsigned NOT NULL default '0',
  `flag` smallint(5) unsigned NOT NULL default '0',
  `owner_user_id` int(10) unsigned NOT NULL default '0',
  `owner_role_tm` int(10) unsigned NOT NULL default '0',
  `money` int(10) NOT NULL default '0',
  `nomoney_days` smallint(5) unsigned NOT NULL default '0',
  `apply_level_limit` smallint(5) unsigned NOT NULL default '0',
  `apply_prof_limit` smallint(5) unsigned NOT NULL default '0',
  `apply_check_type` smallint(5) unsigned NOT NULL default '0',

  PRIMARY KEY  (`area_id`,`union_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `t_union_user_01` (
  `area_id` smallint(5) unsigned NOT NULL default '0',
  `union_id` int(10) unsigned NOT NULL default '0',
  `user_id` int(10) unsigned NOT NULL default '0',
  `role_tm` int(10) unsigned NOT NULL default '0',
  `job` smallint(5) unsigned NOT NULL default '0',
  PRIMARY KEY  (`area_id`,`union_id`,`user_id`,`role_tm`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `t_union_user_require` (
  `area_id` smallint(5) unsigned NOT NULL default '0',
  `union_id` int(10) unsigned NOT NULL default '0',
  `user_id` int(10) unsigned NOT NULL default '0',
  `role_tm` int(10) unsigned NOT NULL default '0',
  `require_time` int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (`area_id`,`union_id`,`user_id`,`role_tm`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#+END_SRC  


** if
#+BEGIN_SRC   sql

 drop table if exists UMAN_UNION.t_union_user_log_%02d 
#+END_SRC  

** 联表 更新

 update    t_seller_student_info t1 , db_weiyi_admin.t_admin_users t2 set  st_application_nick= account where  t2.id= admin_revisiterid  ;

*  gif 屏幕录制
 byzanz-record -d 40 -x 0 -y 0 -w 400 -h 320 byzanz-demo.gif
* convert 
 
  convert -resize 1024x768  xxx.jpg   xxx1.jpg    将图像的像素改为1024*768，注意1024与768之间是小写字母x
  convert -sample 50%x50%  xxx.jpg  xxx1.jpg   将图像的缩减为原来的50%*50% 
* ubuntu   
** /etc/grub.d/10_linux
#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry 'Deepin install' {
  set root=(hd0,3)
  loopback loop  /iso/deepin_2014.1_amd64.iso
  linux (loop)/casper/vmlinuz.efi boot=casper iso-scan/filename=/iso/deepin_2014.1_amd64.iso   noprompt noeject
  initrd (loop)/casper/initrd.lz
}


menuentry 'Deepin install' {
  find --set-root /u.iso 
  loopback loop  /u.iso
  linux (loop)/casper/vmlinuz.efi boot=casper iso-scan/filename=/u.iso   noprompt noeject
  initrd (loop)/casper/initrd.lz
}


* 多线程调试
ps mp 15824 -o THREAD,tid

* vim 乱码
.vimrc :
set fileencodings=utf-8,gb2312,gbk,gb18030
set termencoding=utf-8
set encoding=utf-8

* android tmpdump
adb shell
su 
/data/local/tcpdump

./tcpdump -i any -p -s 0 -w /sdcard/capture.pcap

adb pull /sdcard/capture.pcap capture.pcap 

*  mac pro retina  for linux
**  波浪号
#/etc/rc.local
echo 0 > /sys/module/hid_apple/parameters/iso_layout
** FN 
 echo 2 | sudo tee /sys/module/hid_apple/parameters/fnmode
 echo options hid_apple fnmode=2 | sudo tee -a /etc/modprobe.d/hid_apple.conf
 sudo update-initramfs -u -k all

** find mac info
sudo dmidecode -s system-product-name

** firefox
To fix Firefox open it and go to “about:config”. Search for “layout.css.devPixelsPerPx” and set it to “2” as well.
Some applications still won’t scale. For example Google Chrome and Chromium. That’s a shame, as one of these browsers is needed to watch Netflix. Personally I’m really feeling bummed out by this.
* tex
sudo apt-get install fonts-arphic-ukai fonts-arphic-uming

* nodejs
** cnpm
sudo  npm install -g cnpm --registry=http://registry.npm.taobao.org

* php upload 跨域
if ($_SERVER['REQUEST_METHOD']=='OPTIONS') {
            header("Access-Control-Allow-Origin: *");
            header_remove("Cache-Control");
            header("Access-Control-Allow-Headers: Origin, No-Cache, X-Requested-With, If-Modified-Since, P
ragma, Last-Modified, Cache-Control, Expires, Content-Type, X-E4M-With");
            header("Access-Control-Allow-Methods: GET, POST, OPTIONS" );
            return;
}

* ssh  反向隧道
  http://www.cnblogs.com/nashiyue/p/5233782.html
  ssh -fNR  56006:localhost:22 ybai@118.190.65.189
  iptables -t nat -A PREROUTING -p tcp -m tcp --dport 21016  -j DNAT --to-destination 127.0.0.1:56006

  
* http 缓存  
server {
        listen   80;
        server_name  p.admin-vue.leo1v1.com;

        root /var/www/p.admin.yb1v1.com/vue/dist;
    access_log false;
    error_log /var/log/nginx/error.log;
    location /index.html {
       expires 5s;
   }
}
